### ISSUE TITLE
Global Error Handler

### ISSUE THREAD

**Issue by semihberkayozturk** [vczb/lighthouse-reporter#10]
I would create a folder which contains "Global Error Handler". Can you assign this issue to me?

**Comment by vczb** [comment]
> I would create create a folder which contains "Global Error Handler". Can you assign this issue to me?

Will be very useful, thanks for this

**Comment by semihberkayozturk** [comment]
Thank you @vczb, should I create a new branch or push directly to main?

**Comment by vczb** [comment]
> Thank you @vczb, should I create a new branch or push directly to main?

you need to fork and create a new branch. 

Take a look at this guide if needed: 

https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/
