### ISSUE TITLE
Update contributing section on README

### ISSUE THREAD

**Issue by vczb** [vczb/lighthouse-reporter#16]
Should add clear information about how to contribute. Fork, clone, create a branch, etc... Also, is very important explain how to update your forked repository after some changes ( with rebase ). 

Fell free to research on others repositories and google for examples.

---

thanks

any question I'm available

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, I am in interested. I am just a beginner, started to code just 2 months ago. Can you assign it to me?

**Comment by vczb** [comment]
Hi @ABHIGYAN-MOHANTA , I already assigned you. to this issue are expected a good explanation of the best practices of git usage. Feel free to research and ask

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, made the pr, check it out. Do let me know if you need any changes.

**Comment by ABHIGYAN-MOHANTA** [comment]
Sorry for closing the pr, I will improve on it

**Comment by ABHIGYAN-MOHANTA** [comment]
Done! made the new pr ! Do let me know if you need any changes.

**Comment by ABHIGYAN-MOHANTA** [comment]
Done. Added the CONTRIBUTING.md file

**Comment by vczb** [comment]
closed by #24
