### ISSUE TITLE
Create project LOGO

### ISSUE THREAD

**Issue by vczb** [vczb/lighthouse-reporter#23]
- Design a logo.
- Export the logo as SVG and PNG on the root directory (name logo.svg and logo.png)

**Comment by Guillergood** [comment]
Hello! I can try this one. May I ask you to assign it to me? Also, can you provide more information about the logo? (Any special color/colors, object, form, which file extension...). Thanks in advance

**Comment by vczb** [comment]
> Hello! I can try this one. May I ask you to assign it to me? Also, can you provide more information about the logo? (Any special color/colors, object, form, which file extension...). Thanks in advance

Cool! no idea, feel free to be creative :)

**Comment by vczb** [comment]
> Hello! I can try this one. May I ask you to assign it to me? Also, can you provide more information about the logo? (Any special color/colors, object, form, which file extension...). Thanks in advance

File extension : PNG and SVG

---

references: Feel free to suggest, this project is from web metrics, you can explore it.
