### ISSUE TITLE
Refactor esmodules imports

### ISSUE THREAD

**Issue by vczb** [vczb/lighthouse-reporter#3]
some places are using require and others import. make it homogeneous

**Comment by Zeesky-code** [comment]
Hello, I'll like to work on this. Can I please be assigned to this issue?
🙂

**Comment by vczb** [comment]
> Hello, I'll like to work on this. Can I please be assigned to this issue? slightly_smiling_face

you are welcome :)

**Comment by Zeesky-code** [comment]
Hello, I'm sorry for not working on this since. 
I'm kind of struggling with Typescript as I don't really have any experience in it. I think you can unassign me so someone that can help would have the opportunity to.

I apologize for any inconvenience caused.

**Comment by vczb** [comment]
> Hello, I'm sorry for not working on this since. I'm kind of struggling with Typescript as I don't really have any experience in it. I think you can unassign me so someone that can help would have the opportunity to.
> 
> I apologize for any inconvenience caused.

hi, do not be pressured, take your time to learn and experiment. We don't have to hurry. But if you want to stop is ok, feel free to unassign yourself. your choice, thanks a lot

**Comment by Zeesky-code** [comment]
Ohh, if it's not time-dependent, I can continue with it. 
I just didn't want to hold the project back or anything.

Thanks

**Comment by i-dipanshu** [comment]
Hey @Zeesky-code 
Are you still working on the issue
If i would love take up this issue 1

**Comment by Zeesky-code** [comment]
Hi @i-dipanshu ,  yeah feel free to work on it. 
🙂

**Comment by i-dipanshu** [comment]
Hey @vczb 
Could please assigm me this task

**Comment by i-dipanshu** [comment]
Hey @vczb 
I am getting some errors while updating the imports 
I'd be really helpful if u could help 
Should I list down the issues here and a discord for better interaction

**Comment by vczb** [comment]
> Hey @vczb I am getting some errors while updating the imports I'd be really helpful if u could help Should I list down the issues here and a discord for better interaction

@i-dipanshu  sure, please, share the errors let's try fix it

**Comment by vczb** [comment]
closed by #36
