### ISSUE TITLE
Remove unnecessary data from JSON responses

### ISSUE THREAD

**Issue by vczb** [vczb/lighthouse-reporter#7]
Some responses are returning unnecessary data like `"_id" ` and  `"__v"`

Let's cleanup the response JSON and return only what is needed

In the README we have the API documentation, which should be updated too

**Comment by YasiOnFire** [comment]
Hi, may I be assigned to this please? I have some experience with mongoose.

**Comment by vczb** [comment]
> Hi, may I be assigned to this please? I have some experience with mongoose.

cool! assigned! any questions I'm available =)
